### Crear un nuevo Project
POST http://localhost:8080/api/v1/works HTTP/1.1
Content-Type: application/json
origin: http://localhost:3000

{
  "number_of_work": "4",
  "name": "Keos",
  "period": "ago. 2023 - jan. 2024",
  "description": [
    "Development, integration and deployment in development environments of opensource systems for the automation and registration of clients who visit the main page and/or one of the company s products. These Open Source systems are implemented with React and Django, Elasticsearch, Redis.",
    "For this I also had the opportunity to learn access and management of remote servers"
  ],
  "stack": ["ReactJs", "Django", "Astro", "Tailwind", "Laravel"],
  "image": "https://www.luisgfr.com/static/media/to-do.65855ac56d78ff601e69.webp"
}


### Obtener todos los proyectos
GET http://localhost:8080/api/v1/works HTTP/1.1


### Obtener un proyecto
GET http://localhost:8080/api/v1/projects/65c65bdbfe340e7d80952146 HTTP/1.1

### Actualizar un proyecto
PUT http://localhost:8080/api/v1/projects/65c65bdbfe340e7d80952146 HTTP/1.1
Content-Type: application/json

{
    "title": "To-Do Platform",
    "type_project": "personal",
    "type_platform": "web",
    "links": {
      "github": "https://github.com/luisflr/todo-angular",
      "web": "https://todo-angular-43e05.web.app/"
    },
    "description": "An app where you can create, update or delete your tasks or task lists. The design of this application was inspired by the Trello platform, so it also handles features such as drag-drop.",
    "tech_stack": ["angular", "firebase", "git", "github", "tailwind"],
    "image": "https://www.luisgfr.com/static/media/to-do.65855ac56d78ff601e69.webp"
}

### Delete project
DELETE http://localhost:8080/api/v1/projects/65b95fc4e049703e54264739 HTTP/1.1